import { MigrationInterface, QueryRunner } from 'typeorm';

export class SeedStreetTypes1760371763271 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      INSERT INTO street_types (name) VALUES
      ('Aeroporto'),
      ('Alameda'),
      ('Área'),
      ('Avenida'),
      ('Campo'),
      ('Chácara'),
      ('Colônia'),
      ('Condomínio'),
      ('Conjunto'),
      ('Distrito'),
      ('Esplanada'),
      ('Estação'),
      ('Estrada'),
      ('Fazenda'),
      ('Feira'),
      ('Jardim'),
      ('Ladeira'),
      ('Lago'),
      ('Lagoa'),
      ('Largo'),
      ('Loteamento'),
      ('Núcleo'),
      ('Parque'),
      ('Passarela'),
      ('Pátio'),
      ('Praça'),
      ('Quadra'),
      ('Recanto'),
      ('Residencial'),
      ('Rodovia'),
      ('Rua'),
      ('Setor'),
      ('Sítio'),
      ('Travessa'),
      ('Trecho'),
      ('Trevo'),
      ('Vale'),
      ('Vereda'),
      ('Via'),
      ('Viaduto'),
      ('Viela'),
      ('Beco'),
      ('Travessia'),
      ('Ponte'),
      ('Canal'),
      ('Estrada Vicinal'),
      ('Rodovia Federal'),
      ('Rodovia Estadual'),
      ('Rua de Acesso'),
      ('Via Pública'),
      ('Alto');
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DELETE FROM street_types WHERE name IN (
      'Aeroporto',
      'Alameda',
      'Área',
      'Avenida',
      'Campo',
      'Chácara',
      'Colônia',
      'Condomínio',
      'Conjunto',
      'Distrito',
      'Esplanada',
      'Estação',
      'Estrada',
      'Fazenda',
      'Feira',
      'Jardim',
      'Ladeira',
      'Lago',
      'Lagoa',
      'Largo',
      'Loteamento',
      'Núcleo',
      'Parque',
      'Passarela',
      'Pátio',
      'Praça',
      'Quadra',
      'Recanto',
      'Residencial',
      'Rodovia',
      'Rua',
      'Setor',
      'Sítio',
      'Travessa',
      'Trecho',
      'Trevo',
      'Vale',
      'Vereda',
      'Via',
      'Viaduto',
      'Viela',
      'Beco',
      'Travessia',
      'Ponte',
      'Canal',
      'Estrada Vicinal',
      'Rodovia Federal',
      'Rodovia Estadual',
      'Rua de Acesso',
      'Via Pública',
      'Alto'
      );
    `);
  }
}
