import { MigrationInterface, QueryRunner } from 'typeorm';

export class SeedCategories1760365731538 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      INSERT INTO categories (name) VALUES
      ('CEREAIS E GRÃOS'),
      ('MASSAS E MACARRÃO'),
      ('FARINHAS E FÉCULAS'),
      ('AÇÚCAR E ADOÇANTES'),
      ('ÓLEOS E GORDURAS'),
      ('TEMPEROS E CONDIMENTOS'),
      ('ENLATADOS E CONSERVAS'),
      ('MOLHOS E EXTRATOS'),
      ('CONGELADOS'),
      ('FRIOS E EMBUTIDOS'),
      ('LATICÍNIOS'),
      ('PANIFICADOS E PADARIA'),
      ('BISCOITOS E SNACKS'),
      ('DOCES E SOBREMESAS'),
      ('PRODUTOS NATURAIS E INTEGRAIS'),
      ('ALIMENTOS INFANTIS'),
      ('ÁGUAS'),
      ('REFRIGERANTES'),
      ('SUCOS'),
      ('ENERGÉTICOS'),
      ('BEBIDAS ALCOÓLICAS'),
      ('CAFÉS'),
      ('CHÁS'),
      ('LEITES E BEBIDAS LÁCTEAS'),
      ('SABONETES'),
      ('SHAMPOOS E CONDICIONADORES'),
      ('CREMES E LOÇÕES'),
      ('DESODORANTES'),
      ('HIGIENE BUCAL'),
      ('PRODUTOS PARA BARBEAR'),
      ('ABSORVENTES E CUIDADOS FEMININOS'),
      ('FRALDAS E CUIDADOS COM O BEBÊ'),
      ('DETERGENTES'),
      ('DESINFETANTES'),
      ('SABÃO EM PÓ E LÍQUIDO'),
      ('AMACIANTES'),
      ('LIMPADORES MULTIUSO'),
      ('ESPONJAS E PANOS'),
      ('SACOS DE LIXO'),
      ('UTENSÍLIOS DE COZINHA'),
      ('PRODUTOS PLÁSTICOS'),
      ('PRODUTOS DE ALUMÍNIO'),
      ('VELAS E PILHAS'),
      ('PAPELARIA'),
      ('FERRAMENTAS BÁSICAS'),
      ('EQUIPAMENTOS ELÉTRICOS PEQUENOS'),
      ('PAPEL HIGIÊNICO'),
      ('GUARDANAPOS'),
      ('TOALHAS DE PAPEL'),
      ('UTENSÍLIOS DESCARTÁVEIS'),
      ('RAÇÕES'),
      ('ACESSÓRIOS PARA ANIMAIS'),
      ('HIGIENE ANIMAL'),
      ('SUPLEMENTOS E VITAMINAS'),
      ('PRODUTOS ORTOPÉDICOS'),
      ('MAQUIAGEM'),
      ('PERFUMARIA'),
      ('PRODUTOS PARA CABELO'),
      ('JARDINAGEM');
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DELETE FROM categories WHERE name IN (
        'CEREAIS E GRÃOS',
        'MASSAS E MACARRÃO',
        'FARINHAS E FÉCULAS',
        'AÇÚCAR E ADOÇANTES',
        'ÓLEOS E GORDURAS',
        'TEMPEROS E CONDIMENTOS',
        'ENLATADOS E CONSERVAS',
        'MOLHOS E EXTRATOS',
        'CONGELADOS',
        'FRIOS E EMBUTIDOS',
        'LATICÍNIOS',
        'PANIFICADOS E PADARIA',
        'BISCOITOS E SNACKS',
        'DOCES E SOBREMESAS',
        'PRODUTOS NATURAIS E INTEGRAIS',
        'ALIMENTOS INFANTIS',
        'ÁGUAS',
        'REFRIGERANTES',
        'SUCOS',
        'ENERGÉTICOS',
        'BEBIDAS ALCOÓLICAS',
        'CAFÉS',
        'CHÁS',
        'LEITES E BEBIDAS LÁCTEAS',
        'SABONETES',
        'SHAMPOOS E CONDICIONADORES',
        'CREMES E LOÇÕES',
        'DESODORANTES',
        'HIGIENE BUCAL',
        'PRODUTOS PARA BARBEAR',
        'ABSORVENTES E CUIDADOS FEMININOS',
        'FRALDAS E CUIDADOS COM O BEBÊ',
        'DETERGENTES',
        'DESINFETANTES',
        'SABÃO EM PÓ E LÍQUIDO',
        'AMACIANTES',
        'LIMPADORES MULTIUSO',
        'ESPONJAS E PANOS',
        'SACOS DE LIXO',
        'UTENSÍLIOS DE COZINHA',
        'PRODUTOS PLÁSTICOS',
        'PRODUTOS DE ALUMÍNIO',
        'VELAS E PILHAS',
        'PAPELARIA',
        'FERRAMENTAS BÁSICAS',
        'EQUIPAMENTOS ELÉTRICOS PEQUENOS',
        'PAPEL HIGIÊNICO',
        'GUARDANAPOS',
        'TOALHAS DE PAPEL',
        'UTENSÍLIOS DESCARTÁVEIS',
        'RAÇÕES',
        'ACESSÓRIOS PARA ANIMAIS',
        'HIGIENE ANIMAL',
        'SUPLEMENTOS E VITAMINAS',
        'PRODUTOS ORTOPÉDICOS',
        'MAQUIAGEM',
        'PERFUMARIA',
        'PRODUTOS PARA CABELO',
        'JARDINAGEM'
      );
    `);
  }
}
